nter the grades for 10 students in the following courses:

Student 1:
Enter grade for CSE141: 85
Enter grade for CSE141-lab: 45
Enter grade for CSE578: 78

Student 2:
Enter grade for CSE141: 97
Enter grade for CSE141-lab: 67
Enter grade for CSE578: 9

Student 3:
Enter grade for CSE141: 54
Enter grade for CSE141-lab: 89
Enter grade for CSE578: 99

Student 4:
Enter grade for CSE141: 34
Enter grade for CSE141-lab: 57
Enter grade for CSE578: 78

Student 5:
Enter grade for CSE141: 
8

Enter grade for CSE141-lab: 89
Enter grade for CSE578: 90

Student 6:
Enter grade for CSE141: 90
Enter grade for CSE141-lab: 99
Enter grade for CSE578: 78

Student 7:
Enter grade for CSE141: 55
Enter grade for CSE141-lab: 78
Enter grade for CSE578: 89

Student 8:
Enter grade for CSE141: 8
Enter grade for CSE141-lab: 7
Enter grade for CSE578: 77

Student 9:
Enter grade for CSE141: 77
Enter grade for CSE141-lab: 67
Enter grade for CSE578: 57

Student 10:
Enter grade for CSE141: 57
Enter grade for CSE141-lab: 90
Enter grade for CSE578: 89

Average grade in CSE141: 56.50
Average grade in CSE141-lab: 68.80
Average grade in CSE578: 74.40
Overall average grade in all courses: 66.57


=== Code Execution Successful ===